### ISSUE TITLE
Tracers.console not working

### ISSUE THREAD

**Issue by AlbertoDePena** [fable-elmish/browser#59]
### Description

Program.withTrace Tracers.console not working (Tracers.console comes from Fable.Elmish.Browser). 

### Repro code

```FSharp
module Main

open Elmish
open Elmish.React

// had to add this wrap since Program.withTrace now expects an extra parameter (subId)
let console (msg: 'Msg) (state: 'State) subId =
    printfn "%A" subId
    Tracers.console msg state

Program.mkProgram Application.init Application.update Application.render
|> Program.withReactSynchronous "fable-elmish-app"
#if DEBUG
|> Program.withTrace console
|> Program.withConsoleTrace
#endif
|> Program.run
```

```XML
<TargetFramework>netstandard2.0</TargetFramework>

<ItemGroup>    
    <PackageReference Include="Fable.Elmish.Browser" Version="4.0.0" />    
    <PackageReference Include="Fable.Elmish.React" Version="4.0.0" />
    <PackageReference Include="Feliz" Version="2.0.0-prerelease-003" /> <- this is required for Program.withReactSynchronous  / Program.withReactBatched
    <PackageReference Include="FsToolkit.ErrorHandling" Version="4.2.1" />
  </ItemGroup>
```

[]
2Reflection.js:287 
        
       Uncaught TypeError: Cannot read properties of null (reading 'cases')
    at getUnionCases (Reflection.js:287:11)
    at getCaseName (tracers.fs.js:14:39)
    at getMsgNameAndFields (tracers.fs.js:37:16)
    at console$ (Main.fs.js:10:44)
    at Main.fs.js:17:5
    at Program$4.update (program.fs.js:94:9)
    at Program$4.traceUpdate [as update] (program.fs.js:74:40)
    at processMsgs (program.fs.js:184:48)
    at dispatch (program.fs.js:167:17)
    at onClick (Application.fs.js:80:13)
    at HTMLUnknownElement.callCallback (react-dom.development.js:4164:14)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4213:16)
    at invokeGuardedCallback (react-dom.development.js:4277:31)
    at invokeGuardedCallbackAndCatchFirstError (react-dom.development.js:4291:25)
    at executeDispatch (react-dom.development.js:9041:3)
    at processDispatchQueueItemsInOrder (react-dom.development.js:9073:7)
    at processDispatchQueue (react-dom.development.js:9086:5)
    at dispatchEventsForPlugins (react-dom.development.js:9097:3)
    at react-dom.development.js:9288:12
    at batchedUpdates$1 (react-dom.development.js:26140:12)
    at batchedUpdates (react-dom.development.js:3991:12)
    at dispatchEventForPluginEventSystem (react-dom.development.js:9287:3)
    at dispatchEventWithEnableCapturePhaseSelectiveHydrationWithoutDiscreteEventReplay (react-dom.development.js:6465:5)
    at dispatchEvent (react-dom.development.js:6457:5)
    at dispatchDiscreteEvent (react-dom.development.js:6430:5)

TypeError: Cannot read properties of null (reading 'cases')
getUnionCases
/__parcel_source_root/fable_modules/fable-library.3.7.20/Reflection.js:287:10
  284 | }
  285 | // FSharpType
  286 | export function getUnionCases(t) {
> 287 |     if (t.cases != null) {
      |          ^  288 |         return t.cases();
  289 |     }
  290 |     else {
View compiled
getCaseName
/__parcel_source_root/fable_modules/Fable.Elmish.Browser.4.0.0/tracers.fs.js:14:40
  11 | const t_1 = t_1_mut, acc = acc_mut, x_1 = x_1_mut;
  12 | const caseName = getCaseName_1(x_1);
  13 | let uci_1;
> 14 | const array = getUnionCases(t_1);
     |                            ^  15 | uci_1 = array.find((uci) => (name(uci) === caseName));
  16 | const acc_1 = cons(getCaseName_1(x_1), acc);
  17 | const fields = getCaseFields(x_1);
View compiled
getMsgNameAndFields
/__parcel_source_root/fable_modules/Fable.Elmish.Browser.4.0.0/tracers.fs.js:37:15
  34 |     }
  35 | };
  36 | if (isUnion(x)) {
> 37 |     return getCaseName(t, empty(), x);
     |           ^  38 | }
  39 | else {
  40 |     return ["Msg", x];
View compiled
console$
/__parcel_source_root/Main.fs.js:10:45
   7 | 
   8 | export function console$(msg, state, subId) {
   9 |     toConsole(printf("%A"))(subId);
> 10 |     const patternInput = getMsgNameAndFields(null, msg);
     |                                             ^  11 |     const msg_1_1 = patternInput[0];
  12 |     const fields = patternInput[1];
  13 |     console.log(some(msg_1_1), fields);
View compiled
(anonymous function)
/__parcel_source_root/Main.fs.js:17:4
  14 | }
  15 | 
  16 | ProgramModule_run(ProgramModule_withConsoleTrace(ProgramModule_withTrace((msg_1, state_2, subId) => {
> 17 |     console$(msg_1, state_2, subId);
     |    ^  18 | }, Program_withReactSynchronous("fable-elmish-app", ProgramModule_mkProgram(init, update, render)))));
  19 | 
  20 | 
View compiled
Program$4.update
/__parcel_source_root/fable_modules/Fable.Elmish.4.0.0/program.fs.js:94:8
  91 |     const state = patternInput[0];
  92 |     const cmd = patternInput[1];
  93 |     const subIds = map_1((tuple) => tuple[0], program.subscribe(state));
> 94 |     trace(msg, state, subIds);
     |    ^  95 |     return [state, cmd];
  96 | };
  97 | return new Program$4(program.init, update, program.subscribe, program.view, program.setState, program.onError, program.termination);

**Comment by et1975** [comment]
Thanks, released in 4.0.1.
